# Generated by Django 4.0.1 on 2022-02-02 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EMR_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EMR_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HTS_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HTS_use_and_deployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hts_use_name', models.CharField(max_length=100)),
                ('deployment', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='IL_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Implementation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SDP_agencies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.sdp_agencies')),
            ],
        ),
        migrations.CreateModel(
            name='Facilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mfl_code', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=50)),
                ('sub_county', models.CharField(max_length=50)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('emr_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.emr_status')),
                ('emr_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.emr_type')),
                ('hts_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.hts_status')),
                ('hts_use_and_deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.hts_use_and_deployment')),
                ('il_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.il_status')),
                ('implementation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.implementation')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.owner')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.partners')),
            ],
        ),
    ]
