# Generated by Django 4.0.1 on 2022-02-02 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_emr_status_emr_type_hts_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdp_agencies',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
